export default [
  {
    path: '/user',
    layout: false,
    routes: [
      { path: '/user', routes: [{ name: '登录', path: '/user/login', component: './user/Login' }] },
      { component: './404' },
    ],
  },
  { path: '/welcome', name: '欢迎', icon: 'smile', component: './Welcome' },
  {
    path: '/admin',
    name: '管理页',
    icon: 'crown',
    access: 'canAdmin',
    component: './Admin',
    routes: [
      { path: '/admin/sub-page', name: '二级管理页', icon: 'smile', component: './Welcome' },
      { component: './404' },
    ],
  },
  { name: '查询表格', icon: 'table', path: '/list', component: './TableList' },
  { name: '我的表格', icon: 'table', path: '/mytable', component: './MyTable' },
  { name: 'demo1', icon: 'table', path: '/demo1', component: './Demo01' },
  { name: 'demo2', icon: 'table', path: '/demo2', component: './Demo02' },
  { name: 'demo3', icon: 'table', path: '/demo3', component: './Demo03' },
  { name: 'demo4', icon: 'table', path: '/demo4', component: './Demo04' },
  { name: 'demo5', icon: 'table', path: '/demo5', component: './Demo05' },
  { name: 'demo6', icon: 'table', path: '/demo6', component: './Demo06' },
  { name: 'demo7', icon: 'table', path: '/demo7', component: './Demo07' },
  { name: 'demo8', icon: 'table', path: '/demo8', component: './Demo08' },
  { name: 'demo9', icon: 'table', path: '/demo9', component: './Demo09' },
  { name: 'demo10', icon: 'table', path: '/demo10', component: './Demo10' },
  { name: 'demo11', icon: 'table', path: '/demo11', component: './Demo11' },
  { name: 'demo12', icon: 'table', path: '/demo12', component: './Demo12' },
  { name: 'demo13', icon: 'table', path: '/demo13', component: './Demo13' },
  { name: 'demoTransfer', icon: 'table', path: '/demoTransfer', component: './DemoTransfer' },
  { name: 'demoIframe', icon: 'table', path: '/demoIframe', component: './DemoIframe' },
  { name: 'demoCard', icon: 'table', path: '/demoCard', component: './DemoCard' },
  { name: 'demoScroll', icon: 'table', path: '/demoScroll', component: './DemoScroll' },
  { name: 'demoEditTable', icon: 'table', path: '/demoEditTable', component: './DemoEditTable' },
  { name: 'demoEditTable2', icon: 'table', path: '/demoEditTable2', component: './DemoEditTable2' },
  { name: 'demoEditTable3', icon: 'table', path: '/demoEditTable3', component: './DemoEditTable3' },
  { name: 'demoCut', icon: 'table', path: '/demoCut', component: './DemoCut' },
  { name: 'demoLongList', icon: 'table', path: '/demoLongList', component: './DemoLongList' },
  { name: 'demoTree', icon: 'table', path: '/demoTree', component: './DemoTree' },
  { name: 'demoWxLogin', icon: 'table', path: '/demoWxLogin', component: './DemoWxLogin' },
  { name: 'demoIframeJump', icon: 'table', path: '/demoIframeJump', component: './DemoIframeJump' },
  { name: 'demoContainer', icon: 'table', path: '/demoContainer', component: './DemoContainer' },
  { name: 'demoMenuTree', icon: 'table', path: '/demoMenuTree', component: './DemoMenuTree' },
  { name: 'demoCheck', icon: 'table', path: '/demoCheck', component: './DemoCheck' },
  { name: 'demoCheckGroup', icon: 'table', path: '/demoCheckGroup', component: './DemoCheckGroup' },
  { name: 'demoVideo', icon: 'table', path: '/demoVideo', component: './DemoVideo' },
  { name: 'demoMap', icon: 'table', path: '/demoMap', component: './DemoMap' },
  { name: 'demoMap2', icon: 'table', path: '/demoMap2', component: './DemoMap2' },
  { name: 'demoChart', icon: 'table', path: '/demoChart', component: './DemoChart' },
  { name: 'demoSwiper', icon: 'table', path: '/demoSwiper', component: './DemoSwiper' },
  { name: 'demoPage', icon: 'table', path: '/demoPage', component: './DemoPage' },
  { name: 'demoCross', icon: 'table', path: '/demoCross', component: './DemoCross' },
  { name: 'demoScreen', icon: 'table', path: '/demoScreen', component: './DemoScreen' },
  { name: 'demoAccess', icon: 'table', path: '/demoAccess', component: './DemoAccess' },
  { name: 'antvg61', icon: 'table', path: '/antvg61', component: './Antvg61' },
  { name: 'antvl71', icon: 'table', path: '/antvl71', component: './Antvl71' },
  { name: 'demoTabs', icon: 'table', path: '/demoTabs', component: './DemoTabs' },
  { name: 'demoAnime', icon: 'table', path: '/demoAnime', component: './DemoAnime' },
  { name: 'demoJump', icon: 'table', path: '/demoJump', component: './DemoJump' },
  {
    name: 'demoIframeIn',
    path: '/demoIframeIn',
    component: './DemoIframeJump/iframein',
    hideInMenu: true,
  },
  { path: '/', redirect: '/welcome' },
  { component: './404' },
];
